name: Run tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/authkit/**'
      - 'packages/axios/**'
      - 'packages/core-utils/**'
      - 'packages/drizzle/**'
      - 'packages/oxc/**'
      - 'packages/react/**'
      - 'packages/slidev/**'

jobs:
  test:
    name: Run affected tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Prepare Node.JS and pnpm
        uses: ./.github/actions/prepare-nodejs-pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run affected tests
        run: pnpm turbo run test --filter="...[origin/${{ github.base_ref }}]"
